set_property SRC_FILE_INFO {cfile:C:/Users/Amin/Documents/Computer_Arch_Lab/ARM/ARM_project/vivado_phase1/pin_assignment.xdc rfile:../../../vivado_phase1/pin_assignment.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18                [get_ports clk_0]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14                [get_ports rst_1]
