# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Amin/Documents/Computer_Arch_Lab/ARM/ARM_project/vivado_phase1/pin_assignment.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IF_Stage_Reg_0_0/design_1_IF_Stage_Reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_IF_Stage_Reg_0_0 || ORIG_REF_NAME==design_1_IF_Stage_Reg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IF_1_1/design_1_IF_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_IF_1_1 || ORIG_REF_NAME==design_1_IF_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IDReg_0_0/design_1_IDReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_IDReg_0_0 || ORIG_REF_NAME==design_1_IDReg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ID_0_0/design_1_ID_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ID_0_0 || ORIG_REF_NAME==design_1_ID_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Exe_0_0/design_1_Exe_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Exe_0_0 || ORIG_REF_NAME==design_1_Exe_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ExeReg_0_0/design_1_ExeReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ExeReg_0_0 || ORIG_REF_NAME==design_1_ExeReg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dist_mem_gen_0_0/design_1_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dist_mem_gen_0_0 || ORIG_REF_NAME==design_1_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_StatusReg_0_0/design_1_StatusReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_StatusReg_0_0 || ORIG_REF_NAME==design_1_StatusReg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dist_mem_gen_1_0/design_1_dist_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dist_mem_gen_1_0 || ORIG_REF_NAME==design_1_dist_mem_gen_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MEMReg_0_0/design_1_MEMReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MEMReg_0_0 || ORIG_REF_NAME==design_1_MEMReg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_WbStage_0_0/design_1_WbStage_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_WbStage_0_0 || ORIG_REF_NAME==design_1_WbStage_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hazard_detection_unit_0_0/design_1_hazard_detection_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hazard_detection_unit_0_0 || ORIG_REF_NAME==design_1_hazard_detection_unit_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_forwarding_unit_0_0/design_1_forwarding_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_forwarding_unit_0_0 || ORIG_REF_NAME==design_1_forwarding_unit_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_0/design_1_debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_0 || ORIG_REF_NAME==design_1_debouncer_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
